### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by cjhix** [tr11/antlr4-cobol-copybook-grammar#1]
Would it be possible to add a license file to this repo? This repos would be useful for a project I am working on but I can't use it without a license.

**Comment by tr11** [comment]
Good point, but probably not needed -- this was just a test for the `cobrix` Spark library, which is released under the Apache license. Please see the code at https://github.com/AbsaOSS/cobrix/tree/master/cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr, which implements this repo and contains a few other fixes.

**Comment by tr11** [comment]
Closed by 7aaa9ae59ab114f358d03775c292085dbf172520

**Comment by cjhix** [comment]
Great. Thanks for the link.
